# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto
before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  -
    id: "binary"
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - builds:
      - binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'